name: Update Nginx Web Server on Azure

on:
  push:
    branches:
      - main  # Trigger the workflow when code is pushed to the main branch

jobs:
  update-webserver:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code from the repository
      - name: Check out code
        uses: actions/checkout@v2

      # Step 2: Set up SSH for Azure server
      - name: Set up SSH for Azure server
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.AZURE_SSH_KEY }}

      # Step 3: Copy index.html to the Azure VM
      - name: Copy index.html to Azure VM
        run: |
          scp -o StrictHostKeyChecking=no ./index.html azureuser@20.224.160.198:/usr/share/nginx/html/index.html

      # Step 4: Restart Nginx to apply the changes
      - name: Restart Nginx
        run: |
          ssh -o StrictHostKeyChecking=no azureuser@20.224.160.198 'sudo systemctl restart nginx'
